name: event_bus_starter
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^4.0.0

  add:
    path: ../../packages/add
  setting:
    path: ../../packages/setting

  flutter_modular: ^6.3.4
  event_bus: ^2.0.1

flutter:
  uses-material-design: true
