name: core_network
description: core network package.
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0

dev_dependencies:
  flutter_lints: ^4.0.0
