name: core_util
description: core util package.
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  custom_refresh_indicator: ^4.0.1
  flutter_svg: ^2.0.11
  intl: ^0.19.0
  shimmer: ^3.0.0
