name: workspace_melos

packages:
  - app/**
  - core/**
  - feature/**
  - server/**
  - tool/**

scripts:
  # usage : dart pub run melos run setup
  setup:
    run: |
      melos exec -- rm -rf pubspec.lock &&
      melos run clean &&
      melos run update_packages && 
      melos run pub_get &&
      melos run build_runner

  # usage : dart pub run melos run clean
  clean:
    run: melos exec -- fvm flutter clean

  # usage : dart pub run melos run update_packages
  update_packages:
    run: melos exec -c 4 -- fvm flutter update-packages --force-upgrade

  # usage : dart pub run melos run pub_get
  pub_get:
    run: melos exec -c 1 -- fvm flutter pub get

  # usage : dart pub run melos run build_runner
  build_runner:
    run: melos exec --depends-on="build_runner" -- fvm flutter packages pub run build_runner build --delete-conflicting-outputs

  # usage : dart pub run melos run update
  update:
    run: |
      melos exec -- rm -rf pubspec.lock &&
      melos run clean &&
      melos bootstrap &&
      melos exec -- rm -rf pubspec_overrides.yaml &&
      melos exec -- "rm -rf melos*.iml"
