name: core_flutter_bloc
description: core flutter bloc package.
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  core_bloc:
    path: ../bloc

  flutter_bloc: ^8.1.6
