name: authentication_repository
description: A new Flutter project.
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  cache:
    path: ../cache
  equatable: 2.0.5
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  flutter:
    sdk: flutter
  google_sign_in: 6.2.1
  meta: 1.15.0

dev_dependencies:
  flutter_lints: 3.0.1
