name: feature_calculator
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  calculator_basic_presentation:
    path: ../../presentation
  calculator_basic_domain:
    path: ../../domain
  calculator_basic_data:
    path: ../../data
  calculator_basic_di:
    path: ../../di

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
