include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    camel_case_types: true
    library_names: true
    avoid_catches_without_on_clauses: false
    avoid_catching_errors: true
    avoid_empty_else: true
    unnecessary_brace_in_string_interps: true
    avoid_redundant_argument_values: true
    leading_newlines_in_multiline_strings: true
    directives_ordering: true
    # Formatting
    prefer_single_quotes: true
    lines_longer_than_80_chars: true
    curly_braces_in_flow_control_structures: true
    avoid_print: true
    always_specify_types: false
    sort_constructors_first: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    # Doc comments
    slash_for_doc_comments: true
    require_trailing_commas: true

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/generated/
    - lib/generated/intl/
    - lib/generated/l10n.dart
