include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/generated/
    - lib/generated/intl/
    - lib/generated/l10n.dart
