name: presentation
description: clind presentation package
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  core_bloc:
    path: ../../core/bloc
  core_util:
    path: ../../core/util
