name: clind_server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.6.0
  faker: ^2.2.0
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.4.13
  http: ^1.2.2
  json_serializable: ^6.8.0
  lints: ^5.0.0
