include: package:flutter_lints/flutter.yaml

linter:
  rules:
    directives_ordering: true
    prefer_single_quotes: true
    require_trailing_commas: true
analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
