name: community_di
description: feature community di package
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  community_data:
    path: ../data
  community_domain:
    path: ../domain
  community_presentation:
    path: ../presentation

  core_flutter_bloc:
    path: ../../../core/flutter_bloc

  tool_clind_network:
    path: ../../../tool/clind/network
