name: ui
description: clind ui package
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  presentation:
    path: ../presentation

  di:
    path: ../di

  tool_clind_component:
    path: ../../../tool/clind/component
  tool_clind_theme:
    path: ../../../tool/clind/theme

  core_flutter_bloc:
    path: ../../../core/flutter_bloc
