name: ui
description: clind ui package
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  data:
    path: ../data
  domain:
    path: ../domain
  presentation:
    path: ../presentation
